/*
public class Exception {

  public static void exceptionMain() {
    Scanner in = new Scanner(System.in);
    int T = in.nextInt();
    while (T-- > 0) {
        int n = in.nextInt();
        int p = in.nextInt();
        System.out.println
        Calculator myCalculator = new Calculator();
        try {
            int ans = myCalculator.power(n, p);
            System.out.println(ans);

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

  }

}
*/